name: action-publish

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn --dev

            - name: Publish
              run: yarn app:publish -w
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn --dev

            - name: Publish
              run: yarn app:publish -l
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
